#!/bin/sh
set -eu

TARGET=946713540
DATE='1999-12-31T23:59:00-08:00'

current="$(git log -1 --format='%at %ct')"
if [ "$current" = "$TARGET $TARGET" ]; then
  exit 0
fi

GIT_COMMITTER_DATE="$DATE" git commit -q --amend --no-edit --no-verify --date="$DATE"
